### ISSUE TITLE
Initialization fails if computer name contains non-ASCII characters

### ISSUE THREAD

**Issue by oakgun** [splitio/dotnet-client#185]
Hi, we run into some issues when creating clients with computers with non-ASCII names (Danish, Japanese etc.) in computer names.

> [ERR] Exception caught executing GET https://sdk.split.io/api/splitChanges?since=-1
System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
   at System.Net.Http.HttpConnection.WriteStringAsync(String s)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Splitio.Services.Common.SplitioHttpClient.GetAsync(String url, Boolean cacheControlHeadersEnabled)

I believe this issue is caused by [this line](https://github.com/splitio/dotnet-client/blob/development/src/Splitio/Services/Client/Classes/SelfRefreshingClient.cs#L281). Calling `HttpUtility.HtmlEncode()` here would fix the problem, but this also needs to be decoded on Split's backend. Can you take a look at it?

**Comment by NicoZelaya** [comment]
Hi @oakgun !

My name is Nicolas and I'm part of the SDK team here at Split. 
I'm very sorry for the inconveniences and the slow response here. At a high level this makes sense, we'll take a look at this soon and try to come up with a better way to handle these across the different server side implementations.

If you're currently blocked on integrating Split and have some urgency, would you be so kind to send us an email to support@split.io referencing this thread? So it's easier to exchange information and share interim options with you. 

If you have no rush, we can continue this here! Either myself or someone else from the team will reach out once we make some progress. 

Many thanks for reporting this!

**Comment by sanzmauro** [comment]
hi @sschocke ,
[7.8.1](https://www.nuget.org/packages/Splitio/7.8.1) has been released fixing this issue.

I will close this issue but feel free to reopen it if you need anything else.

Regards,
Mauro
