### ISSUE TITLE
Support for Blazor WASM

### ISSUE THREAD

**Issue by ianmccaul** [splitio/dotnet-client#96]
Would like to be able to run the SDK client side in a Blazor WASM project. But it looks like you are using an unsupported feature of the HttpClientHandler in https://github.com/splitio/dotnet-client/blob/development/src/Splitio/CommonLibraries/SdkApiClient.cs. Namely AutomaticDecompression.

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_AutomaticDecompression(DecompressionMethods value)
   at System.Net.Http.HttpClientHandler.set_AutomaticDecompression(DecompressionMethods value)
   at Splitio.CommonLibraries.SdkApiClient..ctor(String apiKey, Dictionary`2 headers, String baseUrl, Int64 connectionTimeOut, Int64 readTimeout, ITelemetryRuntimeProducer telemetryRuntimeProducer)
   at Splitio.Services.SplitFetcher.Classes.SplitSdkApiClient..ctor(String apiKey, Dictionary`2 headers, String baseUrl, Int64 connectionTimeOut, Int64 readTimeout, ITelemetryRuntimeProducer telemetryRuntimeProducer)
   at Splitio.Services.Client.Classes.SelfRefreshingClient.BuildSdkApiClients()
   at Splitio.Services.Client.Classes.SelfRefreshingClient..ctor(String apiKey, ConfigurationOptions config)
   at Splitio.Services.Client.Classes.SplitFactory.BuildSplitClient()
   at Splitio.Services.Client.Classes.SplitFactory.Client()
   at Splitio.Services.Client.Classes.SplitFactory..ctor(String apiKey, ConfigurationOptions options)

You can do a check to see if the feature is available via HttpClientHandler.SupportsAutomaticDecompression, maybe a place to start.

**Comment by ianmccaul** [comment]
After copying the project and making that tweak it looks like there are CORS issues to the split platform. So likely not just a fix in the sdk itself either. But this would be great to have, otherwise we have to drop down to JS interop, which we can do, but its added complexity.

**Comment by Tim020** [comment]
Hi @ianmccaul,

Thanks for raising this feature request. I'll submit this to the right place internally, but could you let me know whether you are raising this on behalf of a company (and if so who) so we can track appropriately?

Thanks,

Tim

**Comment by ianmccaul** [comment]
> Hi @ianmccaul,
> 
> Thanks for raising this feature request. I'll submit this to the right place internally, but could you let me know whether you are raising this on behalf of a company (and if so who) so we can track appropriately?
> 
> Thanks,
> 
> Tim

Certainly, I am working for a very small early company Suitesy.

**Comment by Tim020** [comment]
Hi @ianmccaul,

I submitted the Feature Request, our product managers go through the new features backlog frequently and will decide if it will be included in a certain version.
We do post all new features in our New Releases page (https://www.split.io/releases/) when they are released, I recommend to subscribe to the page for new updates.

Thanks,

Tim

**Comment by ianmccaul** [comment]
@sanzmauro so was this completed then?

**Comment by sanzmauro** [comment]
Hi @ianmccaul 👋 

It's not completed yet but @Tim020 submitted the Feature Request, so technically is not an issue. So for this reason i closed it. 

As Tim said, you can suscribe to the New Releases page for new updates but also I'll let you know here when I release it.

Does that work for you? 😄 

Best,
Mauro

**Comment by ianmccaul** [comment]
> Hi @ianmccaul 👋
> 
> It's not completed yet but @Tim020 submitted the Feature Request, so technically is not an issue. That's why I closed it.
> 
> As Tim said, you can suscribe to the New Releases page for new updates but also I'll let you know here when I release it.
> 
> Does that work for you? 😄
> 
> Best, Mauro

Yup, thanks for letting me know!
